One voter
hxtk/CSCE240-Final-Project pull request #24
Opened 2016-11-30 21:06 UTC by hbuckner

2016-11-30 21:23 UTC, hxtk requested changes
Documentation should be paired specifically with the method that is being documented

2016-11-30 21:48 UTC, hxtk requested changes
Limit lines to 80 characters.

Ideally, documentation should be a short paragraph for each method.

Finally, start each line with `//` or open with `/*` and close with `*/`, starting each line with `*` for multi-line comments. It is not necessary to close `//`-style comments.

2016-11-30 22:02 UTC, hxtk requested changes
The documentation for ConvertTime is still a single 98 character line.

Additionally, there should be a space following `//`

2016-11-30 22:02 UTC, SolidUmbrella approved these changes

2016-11-30 23:34 UTC, tahwar approved these changes

2016-12-01 01:57 UTC, hxtk approved these changes

2016-12-01 01:57 UTC, merged